Listen 8000
<VirtualHost *:8000>
    ServerName localhost
    DocumentRoot /var/www/html/radius/app/users

    <Directory /var/www/html/radius/app/users>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    ErrorLog /var/log/httpd/daloradius-users-error.log
    CustomLog /var/log/httpd/daloradius-users-access.log combined
</VirtualHost>
