Listen 8080
<VirtualHost *:8080>
    ServerName localhost
    DocumentRoot /var/www/html/radius/app/operators

    <Directory /var/www/html/radius/app/operators>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    ErrorLog /var/log/httpd/daloradius-operators-error.log
    CustomLog /var/log/httpd/daloradius-operators-access.log combined
</VirtualHost>
